Update Entware extras

diff --git a/extras/Entware/bin/eservice b/extras/Entware/bin/eservice
--- a/extras/Entware/bin/eservice
+++ b/extras/Entware/bin/eservice
@@ -1,5 +1,5 @@
 #!/bin/sh
-# /opt/bin/eservice
+# /opt/usr/sbin/eservice
 # This is a small helper script that makes
 # executing Entware's init.d scripts easier
 #
@@ -12,7 +12,20 @@ service="$1"
 action="$2"
 caller="$(basename "$0" .sh)"
 
-if [ -z "$service" ] && [ -z "$action" ]; then
+# Allow swapping parameters - eservice restart dnsmasq
+if [ -n "$action" ]; then
+    case "$service" in
+        start|stop|restart|check|kill|reconfigure)
+            echo "Swapping parameters"
+            tmp="$service"
+            service="$action"
+            action="$tmp"
+        ;;
+    esac
+fi
+
+# List all services and their status
+if [ -z "$action" ] && { [ -z "$service" ] || [ "$service" = "list" ] ; }; then
     ansi_green=$(printf '\033[1;32m')
     ansi_red=$(printf '\033[1;31m')
     ansi_yellow=$(printf '\033[1;33m')
@@ -39,9 +52,10 @@ if [ -z "$service" ] && [ -z "$action" ]; then
     exit
 fi
 
-[ -z "$service" ] && { echo "Service not specified"; exit 1; }
-[ -z "$action" ] && { echo "Action not specified"; exit 1; }
+[ -z "$service" ] && { echo "Service not specified" >&2; exit 1; }
+[ -z "$action" ] && { echo "Action not specified" >&2; exit 1; }
 
+# Perform action on the service (if found)
 for file in $(/opt/bin/find /opt/etc/init.d/ -perm '-u+x' -name 'S*'); do
     check="$(basename "$file")"
     max=3
@@ -57,4 +71,4 @@ for file in $(/opt/bin/find /opt/etc/init.d/ -perm '-u+x' -name 'S*'); do
     done
 done
 
-echo "Service '$service' not found"
+echo "Service '$service' not found" >&2
