Fix whitespace

diff --git a/extras/entware/S25http-to-https-proxy b/extras/entware/S25http-to-https-proxy
--- a/extras/entware/S25http-to-https-proxy
+++ b/extras/entware/S25http-to-https-proxy
@@ -22,42 +22,42 @@ fi
 ARGS="$ARGS > /dev/null 2>&1 &"
 
 download_binary() {
-	[ "$ENABLED" != "yes" ] && return
+    [ "$ENABLED" != "yes" ] && return
 
-	if [ ! -f /opt/bin/http-to-https-proxy ]; then
-		API_URL="https://api.github.com/repos/yeokm1/http-to-https-proxy/releases/latest"
-		API_DATA="$(curl -fsL "$API_URL")"
+    if [ ! -f /opt/bin/http-to-https-proxy ]; then
+        API_URL="https://api.github.com/repos/yeokm1/http-to-https-proxy/releases/latest"
+        API_DATA="$(curl -fsL "$API_URL")"
 
-		if [ -n "$API_DATA" ]; then
-			DOWNLOAD_URL="$(curl -fsL "$API_URL" | grep "browser_download_url.*arm\"" | cut -d : -f 2,3 | tr -d \" | xargs)"
+        if [ -n "$API_DATA" ]; then
+            DOWNLOAD_URL="$(curl -fsL "$API_URL" | grep "browser_download_url.*arm\"" | cut -d : -f 2,3 | tr -d \" | xargs)"
 
-			if [ -n "$DOWNLOAD_URL" ] && echo "$DOWNLOAD_URL" | grep -q "github.com"; then
-				logger -st "$SCRIPT_NAME" "Downloading $DOWNLOAD_URL..."
+            if [ -n "$DOWNLOAD_URL" ] && echo "$DOWNLOAD_URL" | grep -q "github.com"; then
+                logger -st "$SCRIPT_NAME" "Downloading $DOWNLOAD_URL..."
 
-				if ! curl -fsSL "$DOWNLOAD_URL" -o /opt/bin/http-to-https-proxy; then
-					logger -st "$SCRIPT_NAME" "Unable to install - failed to download"
-					exit 1
-				fi
+                if ! curl -fsSL "$DOWNLOAD_URL" -o /opt/bin/http-to-https-proxy; then
+                    logger -st "$SCRIPT_NAME" "Unable to install - failed to download"
+                    exit 1
+                fi
 
-				chmod 755 /opt/bin/http-to-https-proxy
-			else
-				logger -st "$SCRIPT_NAME" "Unable to install - failed to parse returned data"
-				exit 1
-			fi
-		else
-			logger -st "$SCRIPT_NAME" "Unable to install - failed to obtain data from $API_URL"
-			exit 1
-		fi
-	fi
+                chmod 755 /opt/bin/http-to-https-proxy
+            else
+                logger -st "$SCRIPT_NAME" "Unable to install - failed to parse returned data"
+                exit 1
+            fi
+        else
+            logger -st "$SCRIPT_NAME" "Unable to install - failed to obtain data from $API_URL"
+            exit 1
+        fi
+    fi
 }
 
 case "$1" in
     "start")
-		download_binary
-	;;
+        download_binary
+    ;;
     "restart")
-		download_binary
-	;;
+        download_binary
+    ;;
 esac
 
 #shellcheck disable=SC1091
diff --git a/extras/entware/S93fetch-playlists b/extras/entware/S93fetch-playlists
--- a/extras/entware/S93fetch-playlists
+++ b/extras/entware/S93fetch-playlists
@@ -55,107 +55,107 @@ CURL_BINARY="curl"
 
 case "$1" in
     "start")
-		if [ -f "/opt/etc/xupnpd2/xupnpd.cfg" ]; then
-			cru a "$SCRIPT_NAME" "$CRON $SCRIPT_PATH start"
+        if [ -f "/opt/etc/xupnpd2/xupnpd.cfg" ]; then
+            cru a "$SCRIPT_NAME" "$CRON $SCRIPT_PATH start"
 
-			HTTP_IP="$(nvram get lan_ipaddr)"
-			HTTP_PORT="$(grep http_port < /opt/etc/xupnpd2/xupnpd.cfg | cut -d '=' -f 2)"
-			MEDIA_ROOT="$(grep media_root < /opt/etc/xupnpd2/xupnpd.cfg | cut -d '=' -f 2)"
-		else
-			logger -st "$SCRIPT_NAME" "Configuration file not found: /opt/etc/xupnpd2/xupnpd.cfg"
-			exit 1
-		fi
+            HTTP_IP="$(nvram get lan_ipaddr)"
+            HTTP_PORT="$(grep http_port < /opt/etc/xupnpd2/xupnpd.cfg | cut -d '=' -f 2)"
+            MEDIA_ROOT="$(grep media_root < /opt/etc/xupnpd2/xupnpd.cfg | cut -d '=' -f 2)"
+        else
+            logger -st "$SCRIPT_NAME" "Configuration file not found: /opt/etc/xupnpd2/xupnpd.cfg"
+            exit 1
+        fi
 
-		if [ -f "/opt/etc/xupnpd2/playlists.txt" ]; then
-			if [ "$FORCE_HTTP" = "true" ] && [ "$FORCE_HTTPS" = "true" ]; then
-				logger -st "$SCRIPT_NAME" "You can only use either FORCE_HTTP or FORCE_HTTPS"
-				exit 1
-			fi
+        if [ -f "/opt/etc/xupnpd2/playlists.txt" ]; then
+            if [ "$FORCE_HTTP" = "true" ] && [ "$FORCE_HTTPS" = "true" ]; then
+                logger -st "$SCRIPT_NAME" "You can only use either FORCE_HTTP or FORCE_HTTPS"
+                exit 1
+            fi
 
-			[ ! -d "$MEDIA_ROOT" ] && mkdir -vp "$MEDIA_ROOT"
+            [ ! -d "$MEDIA_ROOT" ] && mkdir -vp "$MEDIA_ROOT"
 
-			#shellcheck disable=SC2115
-			rm -fr "$MEDIA_ROOT"/*
+            #shellcheck disable=SC2115
+            rm -fr "$MEDIA_ROOT"/*
 
-			while IFS="" read -r PLAYLIST || [ -n "$PLAYLIST" ]; do
-				PLAYLIST="$(echo "$PLAYLIST" | sed -e "s/\n|\r//")" # Remove Windows line endings
-				BASENAME="$(basename "$PLAYLIST")"
+            while IFS="" read -r PLAYLIST || [ -n "$PLAYLIST" ]; do
+                PLAYLIST="$(echo "$PLAYLIST" | sed -e "s/\n|\r//")" # Remove Windows line endings
+                BASENAME="$(basename "$PLAYLIST")"
 
-				logger -st "$SCRIPT_NAME" "Downloading $PLAYLIST..."
+                logger -st "$SCRIPT_NAME" "Downloading $PLAYLIST..."
 
-				if curl -fsSL "$PLAYLIST" -o "/tmp/$BASENAME"; then
-					[ "$FORCE_HTTP" = true ] && sed -i 's/https:/http:/' "/tmp/$BASENAME"
-					[ "$FORCE_HTTPS" = true ] && sed -i 's/http:/https:/' "/tmp/$BASENAME"
+                if curl -fsSL "$PLAYLIST" -o "/tmp/$BASENAME"; then
+                    [ "$FORCE_HTTP" = true ] && sed -i 's/https:/http:/' "/tmp/$BASENAME"
+                    [ "$FORCE_HTTPS" = true ] && sed -i 's/http:/https:/' "/tmp/$BASENAME"
 
-					if echo "$PLAYLIST" | grep -q "iptv-org.github.io"; then
-						SUBDIR="iptv-org.github.io/$(basename "$(dirname "$PLAYLIST")")"
+                    if echo "$PLAYLIST" | grep -q "iptv-org.github.io"; then
+                        SUBDIR="iptv-org.github.io/$(basename "$(dirname "$PLAYLIST")")"
 
-						[ ! -d "$MEDIA_ROOT/$SUBDIR" ] && mkdir -vp "$MEDIA_ROOT/$SUBDIR"
-						mv -vf "/tmp/$BASENAME" "$MEDIA_ROOT/$SUBDIR/$BASENAME"
-					fi
-				else
-					logger -st "$SCRIPT_NAME" "Failed to download $BASENAME"
-				fi
-			done < "$PLAYLISTS_FILE"
+                        [ ! -d "$MEDIA_ROOT/$SUBDIR" ] && mkdir -vp "$MEDIA_ROOT/$SUBDIR"
+                        mv -vf "/tmp/$BASENAME" "$MEDIA_ROOT/$SUBDIR/$BASENAME"
+                    fi
+                else
+                    logger -st "$SCRIPT_NAME" "Failed to download $BASENAME"
+                fi
+            done < "$PLAYLISTS_FILE"
 
-			if [ -f "$EXCLUDE_FILE" ]; then
-				logger -st "$SCRIPT_NAME" "Filtering playlists..."
+            if [ -f "$EXCLUDE_FILE" ]; then
+                logger -st "$SCRIPT_NAME" "Filtering playlists..."
 
-				find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
-					while IFS="" read -r EXCLUSION || [ -n "$EXCLUSION" ]; do
-						EXCLUSION="$(echo "$EXCLUSION" | sed -e "s/\n|\r//")"
-						PATTERN=$(printf "%s\n" "$EXCLUSION" | sed 's/[]\/$*.^&[]/\\&/g')
-						sed "/$PATTERN/,+1d" -i "$FILE"
-					done < "$EXCLUDE_FILE"
-				done
-			fi
+                find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
+                    while IFS="" read -r EXCLUSION || [ -n "$EXCLUSION" ]; do
+                        EXCLUSION="$(echo "$EXCLUSION" | sed -e "s/\n|\r//")"
+                        PATTERN=$(printf "%s\n" "$EXCLUSION" | sed 's/[]\/$*.^&[]/\\&/g')
+                        sed "/$PATTERN/,+1d" -i "$FILE"
+                    done < "$EXCLUDE_FILE"
+                done
+            fi
 
-			if [ -f "$HANDLERS_FILE" ]; then
-				logger -st "$SCRIPT_NAME" "Inserting handlers..."
+            if [ -f "$HANDLERS_FILE" ]; then
+                logger -st "$SCRIPT_NAME" "Inserting handlers..."
 
-				find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
-					while IFS="" read -r HANDLER || [ -n "$HANDLER" ]; do
-						HANDLER="$(echo "$HANDLER" | sed -e "s/\n|\r//")"
-						PATTERN="$(echo "$HANDLER" | cut -d '|' -f 1)"
-						CONTENT="$(echo "$HANDLER" | cut -d '|' -f 2 | sed 's/[]\/$*.^&[]/\\&/g')"
+                find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
+                    while IFS="" read -r HANDLER || [ -n "$HANDLER" ]; do
+                        HANDLER="$(echo "$HANDLER" | sed -e "s/\n|\r//")"
+                        PATTERN="$(echo "$HANDLER" | cut -d '|' -f 1)"
+                        CONTENT="$(echo "$HANDLER" | cut -d '|' -f 2 | sed 's/[]\/$*.^&[]/\\&/g')"
 
-						sed -E "/EXTINF.*?\-1 tvg/ {N; /$PATTERN/ s/\-1 /\-1 $CONTENT /}" -i "$FILE"
-					done < "$HANDLERS_FILE"
-				done
-			fi
+                        sed -E "/EXTINF.*?\-1 tvg/ {N; /$PATTERN/ s/\-1 /\-1 $CONTENT /}" -i "$FILE"
+                    done < "$HANDLERS_FILE"
+                done
+            fi
 
-			if [ -n "$DEFAULT_HANDLER" ]; then
-				logger -st "$SCRIPT_NAME" "Setting default handler..."
+            if [ -n "$DEFAULT_HANDLER" ]; then
+                logger -st "$SCRIPT_NAME" "Setting default handler..."
 
-				find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
-					while IFS="" read -r HANDLER || [ -n "$HANDLER" ]; do
-						HANDLER="$(echo "$HANDLER" | sed -e "s/\n|\r//")"
-						PATTERN="$(echo "$HANDLER" | cut -d '|' -f 1)"
-						CONTENT="$(echo "$HANDLER" | cut -d '|' -f 2 | sed 's/[]\/$*.^&[]/\\&/g')"
+                find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
+                    while IFS="" read -r HANDLER || [ -n "$HANDLER" ]; do
+                        HANDLER="$(echo "$HANDLER" | sed -e "s/\n|\r//")"
+                        PATTERN="$(echo "$HANDLER" | cut -d '|' -f 1)"
+                        CONTENT="$(echo "$HANDLER" | cut -d '|' -f 2 | sed 's/[]\/$*.^&[]/\\&/g')"
 
-						sed "s/\-1 tvg/\-1 handler=$DEFAULT_HANDLER tvg/" -i "$FILE"
-					done < "$HANDLERS_FILE"
-				done
-			fi
+                        sed "s/\-1 tvg/\-1 handler=$DEFAULT_HANDLER tvg/" -i "$FILE"
+                    done < "$HANDLERS_FILE"
+                done
+            fi
 
-			logger -st "$SCRIPT_NAME" "Fixing metadata..."
+            logger -st "$SCRIPT_NAME" "Fixing metadata..."
 
-			find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
-				sed "s/tvg\-//" -i "$FILE"
-			done
+            find "$MEDIA_ROOT" -type f -name "*.m3u" -o -name "*.m3u8" | while read -r FILE; do
+                sed "s/tvg\-//" -i "$FILE"
+            done
 
-			logger -st "$SCRIPT_NAME" "Forcing media rescan..."
+            logger -st "$SCRIPT_NAME" "Forcing media rescan..."
 
-			"$CURL_BINARY" -fsL "http://$HTTP_IP:$HTTP_PORT/$RESCAN_PATH" > /dev/null
-		else
-			logger -st "$SCRIPT_NAME" "Playlists file not found: $PLAYLISTS_FILE"
-			exit 1
-		fi
+            "$CURL_BINARY" -fsL "http://$HTTP_IP:$HTTP_PORT/$RESCAN_PATH" > /dev/null
+        else
+            logger -st "$SCRIPT_NAME" "Playlists file not found: $PLAYLISTS_FILE"
+            exit 1
+        fi
     ;;
     "stop")
         cru d "$SCRIPT_NAME"
-	;;
+    ;;
     "restart")
         sh "$SCRIPT_PATH" start
-	;;
+    ;;
 esac
